### ISSUE TITLE
Изменение инфы о враче -- множественные баги

### ISSUE THREAD

**Issue by Rif0-coder** [KirillTovpinets/studybelmapo_2019#10]
![изображение](https://user-images.githubusercontent.com/9309156/125243432-c59a7b80-e2f6-11eb-8b7b-3b187d4a48da.png)

Нажал изменить - потом сразу сохранить - не дает. И не понятно почему. Скорее из-за таба с телефоном
![изображение](https://user-images.githubusercontent.com/9309156/125243512-e06cf000-e2f6-11eb-901c-12dcd555899a.png)

Убери валидацию. Рабочих нет уже. 

И должно после того как нажал сохранить - закрывать модалку

**Comment by Rif0-coder** [comment]
![изображение](https://user-images.githubusercontent.com/9309156/125243787-380b5b80-e2f7-11eb-90d8-0e884fc2e6ba.png)
Сходит с ума, когда быстро меняешь значения

**Comment by Rif0-coder** [comment]
![изображение](https://user-images.githubusercontent.com/9309156/125244177-ae0fc280-e2f7-11eb-9099-6f24304f5d6c.png)
История не пишется!

**Comment by KirillTovpinets** [comment]
всё пофиксил
