### ISSUE TITLE
Статистка - действующие - CSS

### ISSUE THREAD

**Issue by Rif0-coder** [KirillTovpinets/studybelmapo_2019#11]
![изображение](https://user-images.githubusercontent.com/9309156/125244443-0646c480-e2f8-11eb-8dac-3866db08934d.png)

CSS

**Comment by Rif0-coder** [comment]
Отчислить досрочно 
![изображение](https://user-images.githubusercontent.com/9309156/125244570-28404700-e2f8-11eb-87ff-c0830ab6fd62.png)

Добавить русккий

**Comment by KirillTovpinets** [comment]
исправлено
