### ISSUE TITLE
нельзя создать нового пользователя 

### ISSUE THREAD

**Issue by Dima331** [KirillTovpinets/studybelmapo_2019#15]
![image](https://user-images.githubusercontent.com/16275510/125246136-0e076880-e2fa-11eb-8223-79d142bd8fb6.png)
нельзя создать нового пользователя, всегда переходит на её

**Comment by KirillTovpinets** [comment]
это просто автозаполнение полей, я сделал специально, чтобы каждый раз все поля не вводить. Но да, надо убрать это
