### ISSUE TITLE
Добавить курс -- множестенные баги

### ISSUE THREAD

**Issue by Rif0-coder** [KirillTovpinets/studybelmapo_2019#9]
![изображение](https://user-images.githubusercontent.com/9309156/125242907-fa5a0300-e2f5-11eb-9a17-de7a2a0bf4ba.png)

![изображение](https://user-images.githubusercontent.com/9309156/125242957-1198f080-e2f6-11eb-9174-35139f33830e.png)

![изображение](https://user-images.githubusercontent.com/9309156/125243108-4e64e780-e2f6-11eb-938d-d2a1971faf4a.png)

Начальная дата < Конечной и не ровна!
Крестик на тултипе кривой
2 дубля курса создается и 2 алертифая
Длительность - нет валидации

**Comment by KirillTovpinets** [comment]
пофиксил
